-- Suppression des tables globales si elles existent encore
DROP TABLE inscriptions CASCADE CONSTRAINTS;
DROP TABLE preinscriptions CASCADE CONSTRAINTS;
DROP TABLE etudiants CASCADE CONSTRAINTS;
DROP TABLE unites_enseignement CASCADE CONSTRAINTS;
DROP TABLE filieres CASCADE CONSTRAINTS;
DROP TABLE formations CASCADE CONSTRAINTS;
DROP TABLE poles CASCADE CONSTRAINTS;
DROP TABLE enseignants CASCADE CONSTRAINTS;
DROP TABLE enos CASCADE CONSTRAINTS;
